import { EmptyState, HudPanel, PageHeader, StatusPill } from "@/components/SofiaPrimitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { shouldOfferVideoUpload } from "@/lib/materialIngestion";
import { AudioLines, FileText, Image, Link2, Loader2, Mic, Pause, Play, Send, UploadCloud, Video, Youtube } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

type CaptureMode = "file" | "text" | "youtube" | "voice";
const modes: Array<{ id: CaptureMode; label: string; icon: typeof FileText }> = [{ id: "file", label: "Arquivo", icon: UploadCloud }, { id: "text", label: "Texto", icon: FileText }, { id: "youtube", label: "YouTube", icon: Youtube }, { id: "voice", label: "Voz", icon: Mic }];

function readAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }
function initialCaptureMode(): CaptureMode { return new URLSearchParams(window.location.search).get("fonte") === "youtube" ? "youtube" : "file"; }

export default function Materials() {
  const utils = trpc.useUtils(); const { data: subjects } = trpc.subjects.list.useQuery(); const [subjectId, setSubjectId] = useState<number | undefined>();
  const { data: materials, isLoading } = trpc.materials.list.useQuery(subjectId ? { subjectId } : undefined); const [mode, setMode] = useState<CaptureMode>(initialCaptureMode); const fileInput = useRef<HTMLInputElement>(null);
  const [title, setTitle] = useState(""); const [text, setText] = useState(""); const [url, setUrl] = useState(""); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [recording, setRecording] = useState(false); const recorderRef = useRef<MediaRecorder | null>(null); const chunksRef = useRef<Blob[]>([]);
  const process = trpc.materials.process.useMutation({ onSuccess: () => { utils.materials.list.invalidate(); utils.dashboard.get.invalidate(); toast.success("Material processado e pronto para estudo."); }, onError: error => { toast.error(error.message); if (shouldOfferVideoUpload(error.message)) setMode("file"); } });
  const upload = trpc.materials.upload.useMutation({ onSuccess: material => { reset(); utils.materials.list.invalidate(); toast.success("Arquivo enviado ao armazenamento seguro."); process.mutate({ id: material.id }); }, onError: error => toast.error(error.message) });
  const createText = trpc.materials.createText.useMutation({ onSuccess: () => { reset(); utils.materials.list.invalidate(); utils.dashboard.get.invalidate(); toast.success("Texto processado e indexado."); }, onError: error => toast.error(error.message) });
  const importYoutube = trpc.materials.importYoutube.useMutation({ onSuccess: () => { reset(); utils.materials.list.invalidate(); utils.dashboard.get.invalidate(); toast.success("Legenda extraída e conteúdo preparado."); }, onError: error => { toast.error(error.message); if (shouldOfferVideoUpload(error.message)) setMode("file"); } });
  const busy = upload.isPending || createText.isPending || importYoutube.isPending || process.isPending;
  const reset = () => { setTitle(""); setText(""); setUrl(""); setSelectedFile(null); if (fileInput.current) fileInput.current.value = ""; };
  const requireSubject = () => { if (!subjectId) { toast.error("Escolha uma disciplina antes de adicionar material."); return false; } return true; };
  const sendFile = async () => { if (!requireSubject() || !selectedFile) return; if (selectedFile.size > 15 * 1024 * 1024) return toast.error("Para este protótipo, envie arquivos de até 15 MB."); const dataUrl = await readAsDataUrl(selectedFile); upload.mutate({ subjectId: subjectId!, title: title.trim() || selectedFile.name.replace(/\.[^/.]+$/, ""), fileName: selectedFile.name, mimeType: selectedFile.type || "application/octet-stream", dataUrl }); };
  const startVoice = async () => { if (!requireSubject()) return; try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream, { mimeType: MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : undefined }); chunksRef.current = []; recorder.ondataavailable = event => { if (event.data.size) chunksRef.current.push(event.data); }; recorder.onstop = () => { stream.getTracks().forEach(track => track.stop()); const file = new File([new Blob(chunksRef.current, { type: recorder.mimeType || "audio/webm" })], `nota-de-voz-${Date.now()}.webm`, { type: recorder.mimeType || "audio/webm" }); setSelectedFile(file); setRecording(false); toast.success("Áudio gravado. Confira o título e envie para transcrição."); }; recorder.start(); recorderRef.current = recorder; setRecording(true); } catch { toast.error("Não foi possível acessar o microfone. Verifique a permissão do navegador."); } };
  const stopVoice = () => recorderRef.current?.stop();
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Ingestão de conhecimento" title={<>Adicionar <span className="text-fuchsia-400">materiais</span></>} description="Seu conteúdo é armazenado com segurança e transformado em uma base de estudo que alimenta resumos, revisões e o tutor." />
    <HudPanel className="mb-6 p-5"><div className="grid gap-5 lg:grid-cols-[.9fr_1.4fr]"><div><p className="hud-label">01 · Disciplina destino</p><select value={subjectId || ""} onChange={event => setSubjectId(event.target.value ? Number(event.target.value) : undefined)} className="mt-2 h-11 w-full rounded-lg border border-cyan-300/15 bg-black/25 px-3 text-sm text-slate-200 outline-none focus:border-cyan-300/55"><option value="">Selecione uma disciplina</option>{subjects?.map(subject => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></div><div><p className="hud-label">02 · Fonte</p><div className="mt-2 flex flex-wrap gap-2">{modes.map(item => <button key={item.id} onClick={() => setMode(item.id)} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-sm transition ${mode === item.id ? "border-cyan-300/50 bg-cyan-300/10 text-cyan-100" : "border-white/5 bg-white/[.02] text-slate-500 hover:text-slate-200"}`}><item.icon className="size-4" />{item.label}</button>)}</div></div></div>
      <div className="mt-6 border-t border-white/5 pt-5">{mode === "file" && <div className="grid gap-4 lg:grid-cols-[1fr_auto]"><div><Input ref={fileInput} type="file" accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/*,audio/*,video/mp4" className="cursor-pointer bg-black/20" onChange={event => { const file = event.target.files?.[0] || null; setSelectedFile(file); if (file && !title) setTitle(file.name.replace(/\.[^/.]+$/, "")); }} /><p className="mt-2 text-xs text-slate-500">PDF, DOCX, imagens, áudios ou vídeos MP4 de até 15 MB. Vídeos de até 30 minutos são transcritos pelo Whisper mesmo sem legenda; o áudio é extraído de forma temporária e segura.</p></div><div className="flex gap-2"><Input className="min-w-52 bg-black/20" placeholder="Título do material" value={title} onChange={event => setTitle(event.target.value)} /><Button disabled={!selectedFile || busy} onClick={sendFile} className="neon-button">{busy ? <Loader2 className="animate-spin" /> : "Enviar"}</Button></div></div>}
      {mode === "text" && <div><Input className="mb-3 bg-black/20" placeholder="Título do material" value={title} onChange={event => setTitle(event.target.value)} /><Textarea value={text} onChange={event => setText(event.target.value)} placeholder="Cole anotações, trechos de livros ou explicações aqui..." className="min-h-36 resize-y bg-black/20" /><div className="mt-3 flex justify-end"><Button disabled={!text.trim() || busy} onClick={() => { if (requireSubject()) createText.mutate({ subjectId: subjectId!, title: title.trim() || "Anotação sem título", text }); }} className="neon-button">{busy ? <Loader2 className="animate-spin" /> : "Processar texto"}</Button></div></div>}
      {mode === "youtube" && <div className="grid gap-3 md:grid-cols-[1fr_1.8fr_auto]"><Input className="bg-black/20" placeholder="Título opcional" value={title} onChange={event => setTitle(event.target.value)} /><Input className="bg-black/20" placeholder="Cole a URL do YouTube com legendas públicas" value={url} onChange={event => setUrl(event.target.value)} /><Button disabled={!url.trim() || busy} onClick={() => { if (requireSubject()) importYoutube.mutate({ subjectId: subjectId!, title: title.trim() || undefined, url }); }} className="neon-button">{busy ? <Loader2 className="animate-spin" /> : "Importar legendas"}</Button><div className="md:col-span-3 flex flex-col gap-3 rounded-xl border border-cyan-300/10 bg-cyan-300/[.035] p-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-slate-400">Links do YouTube usam apenas legendas públicas. Se o vídeo não tiver legenda e você tiver direito de usar o arquivo, envie o MP4: a SOF-IA extrai o áudio e o transcreve com Whisper.</p><Button type="button" variant="outline" onClick={() => setMode("file")} className="shrink-0 border-cyan-300/25 text-cyan-100 hover:bg-cyan-300/10">Enviar MP4</Button></div></div>}
      {mode === "voice" && <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-fuchsia-300/25 bg-fuchsia-300/[.035] p-7 text-center"><div className={`flex size-14 items-center justify-center rounded-2xl border ${recording ? "border-rose-300/70 bg-rose-400/15 text-rose-200" : "border-fuchsia-300/30 bg-fuchsia-300/10 text-fuchsia-200"}`}><Mic className="size-7" /></div><h3 className="mt-4 font-bold text-slate-100">{recording ? "Gravação em andamento" : selectedFile ? "Sua nota de voz está pronta" : "Capture uma ideia por voz"}</h3><p className="mt-1 max-w-md text-sm text-slate-500">Use o microfone para adicionar anotações faladas. O áudio será enviado com segurança e transcrito pelo Whisper.</p><div className="mt-5 flex flex-wrap justify-center gap-2">{recording ? <Button onClick={stopVoice} className="bg-rose-500 text-white hover:bg-rose-400"><Pause className="mr-2 size-4" />Encerrar</Button> : <Button onClick={startVoice} className="soft-button"><Mic className="mr-2 size-4" />Gravar agora</Button>}{selectedFile && !recording && <><Input className="max-w-56 bg-black/20" placeholder="Título da nota" value={title} onChange={event => setTitle(event.target.value)} /><Button disabled={busy} onClick={sendFile} className="neon-button">{busy ? <Loader2 className="animate-spin" /> : "Transcrever e salvar"}</Button></>}</div></div>}</div></HudPanel>
    <div className="mb-4 flex items-center justify-between"><div><p className="hud-label">Biblioteca indexada</p><h2 className="mt-1 text-xl font-bold text-white">Materiais da sua base</h2></div><span className="font-mono text-xs text-slate-500">{materials?.length || 0} registros</span></div>{isLoading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="animate-spin text-cyan-300" /></div> : materials?.length ? <div className="grid gap-3">{materials.map(material => { const Icon = material.type === "youtube" ? Youtube : material.type === "audio" ? AudioLines : material.type === "image" ? Image : material.type === "video" ? Video : FileText; const tone = material.processingStatus === "completed" ? "cyan" : material.processingStatus === "failed" ? "pink" : "amber"; return <HudPanel key={material.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl border border-cyan-300/15 bg-cyan-300/10 text-cyan-200"><Icon className="size-5" /></div><div className="min-w-0 flex-1"><h3 className="truncate font-bold text-slate-100">{material.title}</h3><p className="mt-1 text-xs text-slate-500">{material.fileName || material.sourceUrl || material.type} · {material.extractedText ? `${material.extractedText.length.toLocaleString()} caracteres indexados` : "aguardando processamento"}</p>{material.processingError && <p className="mt-1 text-xs text-rose-300">{material.processingError}</p>}</div><div className="flex items-center justify-between gap-3 sm:justify-end"><StatusPill tone={tone}>{material.processingStatus === "completed" ? "Pronto" : material.processingStatus === "failed" ? "Falhou" : "Pendente"}</StatusPill>{material.processingStatus !== "completed" && <Button size="sm" onClick={() => process.mutate({ id: material.id })} disabled={busy} className="soft-button">Processar</Button>}</div></HudPanel>; })}</div> : <EmptyState icon={<UploadCloud className="size-6" />} title="Sua biblioteca está vazia" description="Envie um PDF, DOCX, foto, vídeo, link do YouTube, texto ou uma nota de voz para ativar as ferramentas de IA." />}
  </div>;
}
