import { HudPanel, PageHeader, StatusPill } from "@/components/SofiaPrimitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, Clock3, Loader2, Target, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function Profile() {
  const utils = trpc.useUtils(); const { data, isLoading } = trpc.profile.get.useQuery(); const [name, setName] = useState(""); const [academicLevel, setAcademicLevel] = useState(""); const [goal, setGoal] = useState(""); const [dailyStudyMinutes, setDailyStudyMinutes] = useState(45);
  useEffect(() => { if (data?.profile) { setName(data.profile.displayName || ""); setAcademicLevel(data.profile.academicLevel || ""); setGoal(data.profile.goal || ""); setDailyStudyMinutes(data.profile.dailyStudyMinutes || 45); } }, [data]);
  const update = trpc.profile.update.useMutation({ onSuccess: () => { utils.profile.get.invalidate(); utils.dashboard.get.invalidate(); toast.success("Perfil salvo. Sua estratégia foi atualizada."); }, onError: error => toast.error(error.message) });
  if (isLoading) return <div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="animate-spin text-cyan-300" /></div>;
  return <div className="mx-auto max-w-5xl"><PageHeader eyebrow="Configuração do aprendiz" title={<>Seu <span className="text-fuchsia-400">perfil</span></>} description="Conte à SOF-IA quais são seus objetivos e sua disponibilidade para que a experiência possa evoluir com você." />
    <HudPanel className="p-5 sm:p-7"><div className="grid gap-7 md:grid-cols-[.42fr_.58fr]"><aside className="border-b border-white/5 pb-6 md:border-b-0 md:border-r md:pb-0 md:pr-7"><div className="flex size-16 items-center justify-center rounded-2xl border border-fuchsia-300/30 bg-fuchsia-300/10 text-fuchsia-200"><UserRound className="size-8" /></div><h2 className="mt-5 text-xl font-bold text-white">Identidade de estudo</h2><p className="mt-2 text-sm leading-6 text-slate-500">Estes dados organizam sua experiência e permitem que o painel exiba um plano compatível com sua rotina.</p><div className="mt-6 space-y-3"><StatusPill tone="cyan">Nível {data?.progress.currentLevel || 1}</StatusPill><p className="text-xs text-slate-600">{data?.progress.totalXp || 0} XP acumulado</p></div></aside><form onSubmit={event => { event.preventDefault(); update.mutate({ displayName: name || undefined, academicLevel: academicLevel || undefined, goal: goal || undefined, dailyStudyMinutes, onboardingCompleted: true }); }} className="space-y-5"><div><label className="hud-label">Como podemos chamar você?</label><Input value={name} onChange={event => setName(event.target.value)} placeholder="Seu nome" className="mt-2 bg-black/20" /></div><div><label className="hud-label">Nível ou preparação</label><select value={academicLevel} onChange={event => setAcademicLevel(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-cyan-300/15 bg-black/25 px-3 text-sm text-slate-200 outline-none"><option value="">Selecione seu contexto</option><option value="Ensino Fundamental">Ensino Fundamental</option><option value="Ensino Médio">Ensino Médio</option><option value="Vestibular/ENEM">Vestibular / ENEM</option><option value="Graduação">Graduação</option><option value="Concurso">Concurso</option><option value="Outro">Outro</option></select></div><div><label className="hud-label">Objetivo principal</label><Textarea value={goal} onChange={event => setGoal(event.target.value)} placeholder="Ex.: dominar biologia para o ENEM em novembro" className="mt-2 min-h-24 bg-black/20" /></div><div><label className="hud-label">Tempo diário disponível</label><div className="mt-2 flex items-center gap-3"><Input type="number" min="10" max="720" value={dailyStudyMinutes} onChange={event => setDailyStudyMinutes(Number(event.target.value))} className="w-28 bg-black/20" /><span className="text-sm text-slate-500">minutos por dia</span></div></div><Button disabled={update.isPending} className="neon-button w-full">{update.isPending ? <Loader2 className="animate-spin" /> : <><Check className="mr-2 size-4" />Salvar estratégia</>}</Button></form></div></HudPanel></div>;
}
