import { EmptyState, HudPanel, PageHeader, StatusPill } from "@/components/SofiaPrimitives";
import { Progress as ProgressBar } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { Activity, BrainCircuit, CalendarDays, Flame, Loader2, Trophy } from "lucide-react";

export default function Progress() {
  const { data, isLoading } = trpc.dashboard.get.useQuery(); if (isLoading) return <div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="animate-spin text-cyan-300" /></div>;
  const subjectCounts = data?.subjects.map(subject => ({ subject, total: data.materials.filter(material => material.subjectId === subject.id).length, mastery: data.subjectMastery.find(item => item.subjectId === subject.id) })) || [];
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Telemetria de aprendizagem" title={<>Sua <span className="text-cyan-300">evolução</span></>} description="Acompanhe sessões, XP e o ritmo da sua construção de conhecimento. As métricas se atualizam conforme você estuda." />
    <div className="grid gap-4 md:grid-cols-4"><HudPanel className="p-5"><Trophy className="size-5 text-fuchsia-300" /><p className="metric-glow mt-5 text-4xl font-black text-fuchsia-200">{data?.progress.totalXp || 0}</p><p className="mt-1 text-sm text-slate-500">XP total conquistado</p></HudPanel><HudPanel className="p-5"><Flame className="size-5 text-amber-300" /><p className="metric-glow mt-5 text-4xl font-black text-amber-200">{data?.progress.currentStreak || 0}</p><p className="mt-1 text-sm text-slate-500">Dias na sequência atual</p></HudPanel><HudPanel className="p-5"><BrainCircuit className="size-5 text-emerald-300" /><p className="metric-glow mt-5 text-4xl font-black text-emerald-200">{data?.masteryScore || 0}%</p><p className="mt-1 text-sm text-slate-500">Score de domínio</p></HudPanel><HudPanel className="p-5"><Activity className="size-5 text-cyan-300" /><p className="metric-glow mt-5 text-4xl font-black text-cyan-200">{data?.studyWeek || 0}</p><p className="mt-1 text-sm text-slate-500">Minutos registrados na semana</p></HudPanel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><HudPanel className="p-5 sm:p-6"><p className="hud-label">Cobertura e domínio</p><h2 className="mt-2 text-xl font-bold text-white">Mapa da sua base</h2>{subjectCounts.length ? <div className="mt-7 space-y-5">{subjectCounts.map(({ subject, total, mastery }) => { const value = mastery?.attempts ? mastery.score : Math.min(100, total * 20); return <div key={subject.id}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-semibold text-slate-200">{subject.name}</span><span className="font-mono text-xs" style={{ color: subject.color }}>{mastery?.attempts ? `${mastery.score}% de domínio` : `${total} material(is)`}</span></div><ProgressBar value={value} className="h-2 bg-white/5" style={{ "--progress-color": subject.color } as React.CSSProperties} /></div>; })}</div> : <div className="mt-6"><EmptyState icon={<BrainCircuit className="size-6" />} title="Aguardando sua primeira disciplina" description="Crie uma disciplina e adicione materiais para iniciar os indicadores." /></div>}</HudPanel>
      <div className="space-y-6"><HudPanel className="p-5 sm:p-6"><p className="hud-label">Pontos de melhoria</p><h2 className="mt-2 text-xl font-bold text-white">Onde reforçar</h2>{data?.improvementAreas.length ? <div className="mt-5 space-y-3">{data.improvementAreas.map(area => <div key={area.subjectId} className="rounded-xl border border-amber-300/15 bg-amber-300/[.04] p-4"><div className="flex justify-between"><span className="font-semibold text-slate-200">{area.name}</span><span className="font-mono text-amber-200">{area.score}%</span></div><p className="mt-2 text-xs leading-5 text-slate-500">Refaça um quiz e revise os flashcards desta disciplina para consolidar os pontos que ainda oscilam.</p></div>)}</div> : <p className="mt-5 text-sm leading-6 text-slate-500">Faça quizzes para a SOF-IA detectar assuntos que merecem uma revisão extra.</p>}</HudPanel><HudPanel className="p-5 sm:p-6"><p className="hud-label">Linha do tempo</p><h2 className="mt-2 text-xl font-bold text-white">Atividade recente</h2>{data?.recentSessions.length ? <div className="mt-6 space-y-4">{data.recentSessions.map(session => <div key={session.id} className="flex gap-3 border-l border-cyan-300/25 pl-4"><div className="mt-1 size-2 rounded-full bg-cyan-300 shadow-[0_0_10px_#22d3ee]" /><div><p className="text-sm font-semibold capitalize text-slate-200">{session.activityType === "flashcard" ? "Revisão de flashcards" : session.activityType === "summary" ? "Resumo gerado" : session.activityType === "quiz" ? "Quiz estudado" : session.activityType === "tutor" ? "Sessão com tutor" : "Material processado"}</p><p className="mt-1 text-xs text-slate-500">{new Date(session.createdAt).toLocaleString("pt-BR")} · +{session.xpEarned} XP · {session.durationMinutes} min</p></div></div>)}</div> : <div className="mt-6"><EmptyState icon={<CalendarDays className="size-6" />} title="Ainda não há atividade" description="Seus resumos, quizzes, conversas e revisões aparecerão aqui como uma linha do tempo." /></div>}</HudPanel></div></div></div>;
}
