import { AIChatBox, type Message } from "@/components/AIChatBox";
import { HudPanel, PageHeader, StatusPill } from "@/components/SofiaPrimitives";
import { trpc } from "@/lib/trpc";
import { BookOpen, BrainCircuit, Loader2, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Tutor() {
  const { data: subjects } = trpc.subjects.list.useQuery(); const [subjectId, setSubjectId] = useState<number | null>(null); const [conversationId, setConversationId] = useState<number>(); const [messages, setMessages] = useState<Message[]>([]);
  const ask = trpc.tutor.ask.useMutation({ onSuccess: data => { setConversationId(data.conversationId); setMessages(previous => [...previous, { role: "assistant", content: data.answer }]); }, onError: error => toast.error(error.message) });
  const send = (question: string) => { setMessages(previous => [...previous, { role: "user", content: question }]); ask.mutate({ conversationId, subjectId, question }); };
  const startNew = () => { setConversationId(undefined); setMessages([]); };
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="RAG · Contexto pessoal" title={<>Tutor <span className="text-fuchsia-400">SOF-IA</span></>} description="Pergunte sobre seus conteúdos. O tutor recupera trechos dos seus materiais antes de responder e sinaliza quando a base não for suficiente." />
    <div className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><HudPanel className="h-fit p-5"><div className="flex size-12 items-center justify-center rounded-2xl border border-fuchsia-300/25 bg-fuchsia-300/10 text-fuchsia-200"><BrainCircuit className="size-6" /></div><h2 className="mt-5 text-xl font-bold text-white">Seu tutor fundamentado</h2><p className="mt-2 text-sm leading-6 text-slate-400">A conversa não usa uma resposta genérica: ela procura primeiro o contexto que você já adicionou à sua base de estudos.</p><div className="mt-6"><p className="hud-label">Filtrar disciplina</p><select value={subjectId || ""} onChange={event => { setSubjectId(event.target.value ? Number(event.target.value) : null); startNew(); }} className="mt-2 h-11 w-full rounded-lg border border-cyan-300/15 bg-black/25 px-3 text-sm text-slate-200 outline-none"><option value="">Todas as disciplinas</option>{subjects?.map(subject => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></div><button onClick={startNew} className="mt-3 text-xs font-semibold text-cyan-200 hover:text-cyan-100">Iniciar nova conversa</button><div className="mt-7 space-y-3 border-t border-white/5 pt-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-cyan-300" /><p className="text-xs leading-5 text-slate-500">As respostas são orientadas pelos materiais que você processou.</p></div><div className="flex gap-3"><BookOpen className="mt-0.5 size-4 shrink-0 text-fuchsia-300" /><p className="text-xs leading-5 text-slate-500">Adicione mais fontes à disciplina para enriquecer as explicações.</p></div></div></HudPanel>
      <HudPanel className="overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/5 px-5 py-4"><div><p className="hud-label">Canal de dúvidas</p><p className="mt-1 text-sm font-semibold text-slate-100">{subjectId ? subjects?.find(subject => subject.id === subjectId)?.name : "Base de estudo completa"}</p></div><StatusPill tone="cyan">Contexto ativo</StatusPill></div><AIChatBox messages={messages} onSendMessage={send} isLoading={ask.isPending} height="580px" className="rounded-none border-0 bg-transparent shadow-none" placeholder="Pergunte algo sobre o que você está estudando..." emptyStateMessage="Qual conceito você quer destravar hoje?" suggestedPrompts={["Explique este assunto de forma simples", "Quais são os pontos mais importantes para revisar?", "Crie uma analogia para entender melhor"]} /></HudPanel></div></div>;
}
